name: 'Windows signtool.exe code sign action V2'
description: 'Sign a file with a pfx certificate. V2'
branding:
  icon: 'award'
  color: 'blue'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the files to sign.'
    required: false
  filename:
    description: 'The file to sign.'
    required: false
  recursive:
    description: 'Recursively search for supported files.'
    required: false
  password:
    description: 'Password to decrypt and import the certificate'
    required: true
  certificatesha1:
    description: 'The sha1 or fingerprint of the certificate'
    required: false
  certificatename:
    description: 'The Name of the certificate'
    required: false
  description:
    description: 'Description of the signed content (signtool /d flag)'
    required: false
  timestampUrl:
    description: 'URL of the timestamp server'
    required: false
    default: 'http://timestamp.digicert.com'

runs:
  using: 'node20'
  main: 'dist/index.js'
